### ISSUE TITLE
[DELETE] Review 모델에서 getReviewCreatedAt 삭제

### ISSUE THREAD

**Issue by jelliijoa** [TEAM-SMCS4K/Movier#49]
## 🎬 Desciption

리뷰 모델을 아래와 같이 수정했습니다.
- Review에서 getReviewCreatedAt 삭제
- ReviewList를 MyPageReview로 rename
- ReviewDetail이 MyPageReview 상속 받도록 함

## 🎬 To-do

- [x] Review에서 getReviewCreatedAt 삭제
- [x] ReviewList를 MyPageReview로 rename
- [x] ReviewDetail이 MyPageReview 상속 받도록 함

## 🎬 ETC

2024.05.27
