### ISSUE TITLE
[FEAT] myReview 뷰 수정 및 리뷰 상세 조회 기능 구현

### ISSUE THREAD

**Issue by jelliijoa** [TEAM-SMCS4K/Movier#58]
## 🎬 Desciption

공통 컴포넌트를 사용하여 myReview 뷰를 구현했습니다.
myPage에서 리뷰가 없을 때로 분기 처리한 뷰를 수정했습니다.
myPage에서 myReview, myReview에서 각 뷰로 넘어갈 때 파라미터 전달하도록 수정 후 리뷰 상세 조회 기능을 구현했습니다.
detailsComponent에서 해당 리뷰의 영화 데이터를 불러오는 기능을 구현했습니다.

## 🎬 To-do

- [x] myPage에서 myReview로 리다이렉션 시 reviewId 넘겨주도록 수정
- [x] myPage에서 수정하기 버튼 누르면 editReview로 리다이렉션, 삭제하기 버튼 누르면 리뷰 삭제하는 기능 구현
- [x] myPage에서 유저가 작성한 리뷰가 없을 때 아래 reviews 박스 깨지는 현상 수정
<br/>

- [x] myReview 뷰 구현
- [x] myReview에서 editReview로 리다이렉션 시 reviewId 넘겨주도록 수정
- [x] myReview에서 사용자가 삭제 버튼 누르면 "삭제하시겠습니까?" alert 추가 후 yes 클릭한 경우에만 삭제하도록 분기 처리
<br/>

- [x] detailsComponent.css에서 영화 장르 태그 -> 피그마와 같은 색상 사용하도록 background, color 변경
- [x] detailsComponent에서 해당 리뷰의 영화 데이터 불러오는 기능 구현

## 🎬 ETC

나눠서 푸쉬했어야 하는데 한 번에 개발하다보니 한 commit에 뷰&기능 추가, 변경이 많이 들어가게 되었습니다. 양해 부탁드립니다!! 😅
2024.05.28
