### ISSUE TITLE
[REFACTOR] 프로시저 에러 분기에 따른 소셜 로그인, 공감 개수 확인 기능 수정

### ISSUE THREAD

**Issue by sung-silver** [TEAM-SMCS4K/Movier#62]
## 🎬 Desciption

- 테이블 제약조건 추가
- [프로시저] check_sympathy 입력값 검증 및 에러 분기 처리
- [함수] get_member_id_by_kakao_platform_id 에러 분기 처리
- [프로시저] insert_member 입력값 검증 에러 처리
- 소셜 로그인 기능 프로시저, 함수 변경에 따라 리팩토링
- 공감 개수 확인 기능 프로시저 변경에 따라 리팩토링

## 🎬 To-do

- [x] 테이블 제약 조건 추가
- [x] 프로시저, 함수 수정
- [x] 소셜 로그인 리팩토링
- [x] 공감 개수 확인 기능 리팩토링

## 🎬 ETC

- 마감: 2024.05.30 (목)
