### ISSUE TITLE
[FIX] 리뷰 작성, 리뷰 수정, 나의 리뷰 뷰 css 수정

### ISSUE THREAD

**Issue by kcy24** [TEAM-SMCS4K/Movier#89]
## 🎬 Desciption

리뷰 작성, 리뷰 수정, 나의 리뷰 뷰 css 수정

## 🎬 To-do

- [x] writeReveiw.css 수정
- [x] detailsComponent.css 수정
- [x] myReview.css 수정
- [x] starRating.css 수정

## 🎬 ETC

2024.06.01
